### ISSUE TITLE
Election test TestUnsupportedElectionParams() is expecting the incorrect reason code

### ISSUE THREAD

**Issue by jeremyrandnokia** [openconfig/gribigo#125]
In this test, an election id is sent in all primary mode.  According to the gribi.proto file:

```
    // If the server is currently operating in ALL_PRIMARY mode the server
    // should return an error specifying ELECTION_ID_IN_ALL_PRIMARY reason. The
    // status (canonical error code) should be FAILED_PRECONDITION.
```

But the test is currently expecting `fluent.ParamsDifferFromOtherClients`.  Shouldn't this be `fluent.ElectionIDNotAllowed`?

**Comment by robshakir** [comment]
Thanks for catching this, yes -- this looks to be a copy&paste error. Will submit a fix.
