### ISSUE TITLE
Server implementation should return both RIB_ACK and FIB_ACK in the session of RIB_AND_FIB_ACK

### ISSUE THREAD

**Issue by xw-g** [openconfig/gribigo#135]
Current server.go implementation [returns only `FIB_ACK` in a `RIB_AND_FIB_ACK` session](https://github.com/openconfig/gribigo/blob/a834d623ec87476c5e9cb1efbd5dd1b532fadda3/server/server.go#L850-L856). 

Indeed we [don't need to return both `RIB_ACK` and  `FIB_ACK` in a `RIB_AND_FIB_ACK` session](https://github.com/openconfig/gribi/blob/7d876062a31f072bd5b9159b522120ef3fdb5f44/v1/proto/service/gribi.proto#L393-L397), but it does allow so. Different vendor HW&SW arch might choose either way in this case. 

Maybe we should consider making our server implementation returns both `RIB_ACK` and `FIB_ACK` mainly for the implementation reference and for the benefit of test coverage (e.g. issue #130 )

**Comment by robshakir** [comment]
Will be fixed in #179.

**Comment by robshakir** [comment]
Fixed by #179.
