### ISSUE TITLE
issue with client connection order

### ISSUE THREAD

**Issue by bkreddy14** [openconfig/gribigo#153]
see some times the test "TestParamsDifferFromOtherClients" in election.go fails due to client connection order.  I see some times client B sends requests modify request first and clientA modify request fails  so better to add the client A validation before sending Client B modify request that would avoid random failures due to timing issues .

move below code from line 164 to 157. 
'''
	clientAErr := awaitTimeout(context.Background(), clientA, t, time.Minute)
	if err := clientAErr; err != nil {
		t.Fatalf("did not expect error from server in client A, got: %v", err)
	}
'''

**Comment by xw-g** [comment]
should be solved by #157. thanks for bringing up the issue.
