### ISSUE TITLE
Compliance test FlushNIUnspecified() is expecting an error which differs from the gribi.proto file comments

### ISSUE THREAD

**Issue by jeremyrandnokia** [openconfig/gribigo#160]
From gribi.proto:

```
  // network_instance specifies the Network Instance that should be flushed. If
  // the client specifies neither name nor all the server should respond with
  // an error specifying the INVALID_ARGUMENT canonical error code, and the
  // UNSPECIFIED_NETWORK_INSTANCE error code.
```

However, the FlushNIUnspecified() test is expecting codes.FailedPrecondition.  I believe it should instead expect codes.InvalidArgument based on what gribi.proto says.

**Comment by xw-g** [comment]
Thanks for catching this, @jeremyrandnokia. I'll file a quick PR to update it.

**Comment by xw-g** [comment]
https://github.com/openconfig/gribigo/pull/161

**Comment by jeremyrandnokia** [comment]
The updated testcase looks good.  Thanks for the fix!
