### ISSUE TITLE
need fluent api for IPv6Entry()

### ISSUE THREAD

**Issue by singh-prem** [openconfig/gribigo#207]
[featureprofile](https://github.com/openconfig/featureprofiles/pull/2207)  has scenario where gRIBI should inject an IPv6Entry enrty on the DUT. An enhancement of fluent api for the same will be helpful.

**Comment by robshakir** [comment]
We can add this -- what is the priority for doing so? (Adding testing for this requires adding IPv6 support to the fake server too, which will be needed for IPv6 gRIBI compliance tests to be validated.)

**Comment by robshakir** [comment]
The chain of PRs here adds support including testing for IPv6 to gribigo:

* #208 
* #209 
* #210 
* #211 
* #212 
* #213 
* #214 
* #215 

We should make sure that we add basic tests to `compliance/compliance.go` for IPv6. I've created the first of these - but it does not completely cover everything required.

**Comment by singh-prem** [comment]
> We can add this -- what is the priority for doing so? (Adding testing for this requires adding IPv6 support to the fake server too, which will be needed for IPv6 gRIBI compliance tests to be validated.)
Thanks @robshakir for quick response. This is needed in one of our immediate deliverable, making priority high.

**Comment by singh-prem** [comment]
Thanks, Updated code is working fine. Closing the issue.
